route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'telegram'
  routes:
#    - receiver: 'web.hook'
#      matchers:
#      - severity="warning"
    - receiver: 'telegram'
      matchers:
      - severity="critical"
receivers:
#  - name: 'web.hook'
#    webhook_configs:
#      - url: 'http://192.168.11.222:5001/'
  - name: 'telegram' 
    telegram_configs: 
    - chat_id: -4277477785
      parse_mode: 'Markdown'  
      bot_token: <bot_token>
      message: "Some text for notify"
#inhibit_rules:
#  - source_match:
#      severity: 'critical'
#    target_match:
#      severity: 'warning'
#    equal: ['alertname', 'dev', 'instance']
